# Generated by Django 4.2.30 on 2026-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='has_existing_portfolio',
            field=models.BooleanField(default=False, verbose_name='Имел портфель до входа в сервис'),
        ),
    ]
