# Generated by Django 4.2.27 on 2026-01-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=36, verbose_name='ID сессии')),
                ('name', models.CharField(default='Мой портфель', max_length=100, verbose_name='Название портфеля')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальная сумма ($)')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('target_years', models.IntegerField(verbose_name='Горизонт инвестирования (лет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ актива')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название актива')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля в портфеле (%)')),
                ('initial_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена при покупке ($)')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Актив портфеля',
                'verbose_name_plural': 'Активы портфеля',
            },
        ),
    ]
