# Generated by Django 4.2.28 on 2026-02-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_add_contributions_and_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вывода ($)')),
                ('withdrawn_at', models.DateField(auto_now_add=True, verbose_name='Дата вывода')),
                ('value_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость портфеля после вывода ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Вывод из портфеля',
                'verbose_name_plural': 'Выводы из портфеля',
                'ordering': ['-withdrawn_at'],
            },
        ),
    ]
