# Generated by Django 4.2.30 on 2026-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_add_portfolio_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Импортирован пользователем'),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='is_recommended',
            field=models.BooleanField(default=True, verbose_name='Входит в рекомендуемый ТОП-10'),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='purchased_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
    ]
