# Generated by Django 4.2.30 on 2026-04-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_portfolio_is_imported_portfolioasset_is_recommended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_symbol', models.CharField(max_length=10, verbose_name='Из (символ)')),
                ('from_units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Из (количество)')),
                ('from_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Из (цена $)')),
                ('to_symbol', models.CharField(max_length=10, verbose_name='В (символ)')),
                ('to_units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='В (количество)')),
                ('to_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='В (цена $)')),
                ('to_units_expected', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Ожидаемое количество по рынку')),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комиссия / разница ($)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('swapped_at', models.DateField(auto_now_add=True, verbose_name='Дата обмена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='portfolios.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Обмен активов',
                'verbose_name_plural': 'Обмены активов',
                'ordering': ['-swapped_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioContributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ актива')),
                ('units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество единиц')),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена покупки ($)')),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма позиции ($)')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolios.portfoliocontribution', verbose_name='Взнос')),
            ],
            options={
                'verbose_name': 'Позиция взноса',
                'verbose_name_plural': 'Позиции взносов',
            },
        ),
    ]
