# Generated by Django 4.2.30 on 2026-05-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_contribution_items_and_swaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кошелька')),
                ('type', models.CharField(choices=[('exchange', 'Биржа'), ('hot', 'Горячий кошелёк'), ('cold', 'Холодный кошелёк'), ('bank', 'Банковский счёт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип кошелька')),
                ('is_default', models.BooleanField(default=False, verbose_name='Кошелёк по умолчанию')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='portfolios.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('portfolio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WalletHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ актива')),
                ('units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество единиц')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.wallet', verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Баланс на кошельке',
                'verbose_name_plural': 'Балансы на кошельках',
                'unique_together': {('wallet', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ актива')),
                ('from_units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Списано (количество)')),
                ('to_units', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Зачислено (количество)')),
                ('fee_units', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Комиссия (в единицах актива)')),
                ('fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комиссия ($)')),
                ('occurred_on', models.DateField(verbose_name='Дата перевода')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='portfolios.wallet', verbose_name='Откуда (кошелёк)')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfers', to='portfolios.portfolio', verbose_name='Портфель')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='portfolios.wallet', verbose_name='Куда (кошелёк)')),
            ],
            options={
                'verbose_name': 'Перевод между кошельками',
                'verbose_name_plural': 'Переводы между кошельками',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'occurred_on'], name='portfolios__portfol_077dd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='HoldingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_before', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Баланс до (количество)')),
                ('units_after', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Баланс после (количество)')),
                ('delta', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Изменение (units_after - units_before)')),
                ('value_delta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Изменение стоимости ($)')),
                ('reason', models.CharField(choices=[('network_fee', 'Комиссия сети'), ('exchange_fee', 'Комиссия биржи'), ('reconciliation', 'Сверка баланса'), ('input_error', 'Исправление ошибки ввода'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Причина')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий')),
                ('occurred_on', models.DateField(verbose_name='Дата корректировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='portfolios.walletholding', verbose_name='Баланс на кошельке')),
            ],
            options={
                'verbose_name': 'Корректировка баланса',
                'verbose_name_plural': 'Корректировки балансов',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['holding', 'occurred_on'], name='portfolios__holding_50eb49_idx')],
            },
        ),
    ]
