# Generated by Django 4.2.30 on 2026-05-06 07:32
#
# Data migration: backfill default Wallet и WalletHolding для существующих портфелей.
# Реализация по плану PLAN06-realization.md (Агент 6).

from decimal import Decimal

from django.db import migrations


DEFAULT_WALLET_NAME = "Общий кошелёк"
DEFAULT_WALLET_TYPE = "other"


def backfill_default_wallets(apps, schema_editor):
    """Создаёт default Wallet и WalletHolding для существующих портфелей.

    Логика:
        * для каждого Portfolio — создать default Wallet (name="Общий кошелёк",
          is_default=True, type="other"), если его ещё нет;
        * для каждого PortfolioAsset — создать WalletHolding в default-кошельке
          (symbol = asset.symbol, units = asset.units), без дублирования.

    Важно:
        * не дублируем holdings (unique_together (wallet, symbol));
        * существующие данные не ломаем — изменяем только новые сущности.
    """
    Portfolio = apps.get_model("portfolios", "Portfolio")
    Wallet = apps.get_model("portfolios", "Wallet")
    WalletHolding = apps.get_model("portfolios", "WalletHolding")

    for portfolio in Portfolio.objects.all():
        # 1) Берём или создаём default-кошелёк.
        default_wallet = (
            Wallet.objects.filter(portfolio=portfolio, is_default=True).first()
        )

        if default_wallet is None:
            # Если кошелька с таким именем уже нет — создаём новый default.
            # Если же кошелёк с именем "Общий кошелёк" существует, но не помечен
            # как default — помечаем его, чтобы соблюсти инвариант.
            existing_named = Wallet.objects.filter(
                portfolio=portfolio, name=DEFAULT_WALLET_NAME
            ).first()

            if existing_named is not None:
                existing_named.is_default = True
                existing_named.save(update_fields=["is_default", "updated_at"])
                default_wallet = existing_named
            else:
                default_wallet = Wallet.objects.create(
                    portfolio=portfolio,
                    name=DEFAULT_WALLET_NAME,
                    type=DEFAULT_WALLET_TYPE,
                    is_default=True,
                    note="",
                )

        # 2) Для каждого актива портфеля создаём WalletHolding (если ещё нет).
        for asset in portfolio.assets.all():
            symbol = (asset.symbol or "").strip()
            if not symbol:
                continue

            units = asset.units if asset.units is not None else Decimal("0")

            # Не дублируем — get_or_create по (wallet, symbol).
            holding, created = WalletHolding.objects.get_or_create(
                wallet=default_wallet,
                symbol=symbol,
                defaults={"units": units},
            )
            # Если holding уже существовал — оставляем его units как есть,
            # чтобы не затереть данные, добавленные вручную.
            if created:
                continue


def reverse_backfill(apps, schema_editor):
    """Откат backfill.

    Удаляем только те WalletHolding, которые лежат в default-кошельках, и сами
    default-кошельки. Это безопасный no-op для случаев, когда миграция уже
    применена и пользователь успел поработать с данными — но в общем случае
    откат вернёт состояние «до backfill» для нетронутых портфелей.
    """
    Wallet = apps.get_model("portfolios", "Wallet")
    WalletHolding = apps.get_model("portfolios", "WalletHolding")

    default_wallets = Wallet.objects.filter(
        is_default=True, name=DEFAULT_WALLET_NAME
    )
    WalletHolding.objects.filter(wallet__in=default_wallets).delete()
    default_wallets.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_wallet_walletholding_wallettransfer_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_default_wallets,
            reverse_code=reverse_backfill,
        ),
    ]
