# Generated by Django 4.2.30 on 2026-05-18 11:44
#
# Schema + data migration: добавляет Portfolio.base_currency, создаёт модель
# FiatCashFlow и выполняет data-backfill для существующих портфелей.
# Реализация по плану PLAN11.md (Агент A2).

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def backfill_base_currency(apps, schema_editor):
    """Проставляет base_currency='USD' всем существующим портфелям.

    Хотя у поля стоит default='USD' на уровне Django/БД и AddField уже
    инициализировал колонку этим значением, делаем явный update — это
    закрепляет инвариант «все ранее созданные портфели в USD» и совпадает
    со спецификацией A2 в PLAN11.md.

    FiatCashFlow на этом этапе пуст — отдельный backfill для него не нужен.
    """
    Portfolio = apps.get_model("portfolios", "Portfolio")
    Portfolio.objects.update(base_currency="USD")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_portfolioswap_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='base_currency',
            field=models.CharField(choices=[('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)')], default='USD', max_length=3, verbose_name='Базовая валюта для P&L по фиату'),
        ),
        migrations.CreateModel(
            name='FiatCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Внесение фиата'), ('withdrawal', 'Вывод фиата')], max_length=12, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('USD', 'Доллар США (USD)'), ('EUR', 'Евро (EUR)')], max_length=3, verbose_name='Валюта операции')),
                ('fx_rate_to_base', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12, verbose_name='Курс currency → portfolio.base_currency')),
                ('occurred_on', models.DateField(verbose_name='Дата операции')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat_cash_flows', to='portfolios.portfolio', verbose_name='Портфель')),
            ],
            options={
                'verbose_name': 'Фиатное движение',
                'verbose_name_plural': 'Фиатные движения',
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['portfolio', 'kind', 'occurred_on'], name='portfolios__portfol_925768_idx')],
            },
        ),
        migrations.RunPython(
            backfill_base_currency,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
